# Generated by Django 2.2 on 2020-01-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MLMHELPDESK', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mmlticket',
            old_name='user_id',
            new_name='number',
        ),
    ]
