# Generated by Django 2.2 on 2020-01-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLMUSERS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='AdharCard',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='AltMobileNumber',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='Pancard',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
