# Generated by Django 2.2 on 2020-01-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MLMUSERS', '0002_auto_20200107_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='number',
            new_name='email',
        ),
    ]
