# Generated by Django 2.2 on 2020-01-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLMAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='X6LZH9', max_length=6, unique=True),
        ),
    ]
