# Generated by Django 2.2 on 2020-01-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLMAPP', '0002_auto_20200114_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='2CJRB5', max_length=6, unique=True),
        ),
    ]
