# Generated by Django 2.2 on 2020-01-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('EffectiveStartDate', models.DateField(default='')),
                ('EffectiveEndDate', models.DateField(default='')),
                ('state', models.IntegerField(default='')),
                ('status', models.IntegerField(default='')),
            ],
        ),
    ]
