# Generated by Django 2.2 on 2020-01-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mobilenumber',
            field=models.CharField(default='', max_length=100),
        ),
    ]
