# Generated by Django 2.2 on 2020-01-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200104_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
