# Generated by Django 2.2 on 2020-01-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200104_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
