# Generated by Django 2.2 on 2020-01-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200104_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
