# Generated by Django 2.2 on 2020-01-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLMAPP', '0002_auto_20200106_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='BPG5IF', max_length=8, unique=True),
        ),
    ]
