# Generated by Django 2.2 on 2020-01-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLMAPP', '0003_auto_20200107_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='LDYTO3', max_length=6, unique=True),
        ),
    ]
