# Generated by Django 2.2 on 2020-01-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLMAPP', '0004_auto_20200107_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='DGM92J', max_length=6, unique=True),
        ),
    ]
