# Generated by Django 2.2 on 2020-01-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLMAPP', '0006_auto_20200107_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='Z7IUG1', max_length=6, unique=True),
        ),
    ]
