# Generated by Django 2.2 on 2020-01-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLMAPP', '0007_auto_20200107_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='MQ0PJV', max_length=6, unique=True),
        ),
    ]
