# Generated by Django 2.2 on 2020-01-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLMAPP', '0008_auto_20200107_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='NNKHRC', max_length=6, unique=True),
        ),
    ]
